version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/api_react_native
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    ports:
      - "8080:8080"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017

volumes:
  mongo-data: